# Project

project.fullname = "Corpus der amtlichen Entscheidungssammlung des Bundesverfassungsgerichts"
project.shortname = "C-BVerfGE"
project.author = "Seán Fobbe"



# License

license.data = "Creative Commons Zero 1.0 Universal"
license.code = "MIT-0"



# Digital Object Identifier (DOI)

doi.data.concept = "10.5281/zenodo.3831111" # do not change
doi.data.version = "10.5281/zenodo.10783177" # checked

doi.software.concept = "10.5281/zenodo.4265933" # do not change
doi.software.version = "10.5281/zenodo.10783178" # checked

doi.personendaten = "10.5281/zenodo.4568682" # checked
doi.aktenzeichen = "10.5281/zenodo.4569564" # checked



# Annotation

annotate.toggle = true # Wenn dieser Modus aktiviert ist wird  mittels spacyr eine zusätzliche Variante des Datensatzes mit umfangreichen linguistischen Annotationen berechnet. Sehr rechenintensiv!



# Parallelization

cores.max = true  # Ob die maximale Anzahl an logischen Kernen genutzt werden soll; Möglichkeiten sind "true" oder "false"
cores.number = 8   # Die Anzahl Rechtenkerne, die verwendet werden soll; wird nur berücksichtigt falls "cores.max" auf "false" steht


parallel.extractPDF = true
parallel.lingsummarize = true
parallel.spacyparse = false
parallel.multihashes = true



# Download
download.timeout = 600			# Timeout für Downloads



# Quanteda
quanteda.tokens_locale = "de_DE" # Locale in denen Tokens analyisert werden



# Knitr

fig.format = [ "pdf", "png" ] 	# Ausgabe-Format für Diagramme
fig.dpi = 300     	 	# Auflösung für Diagramme
fig.align = "center"    	# Ausrichtung von Diagrammen im Compilation Report



# Frequenztabellen: Ignorierte Variablen
#' **Hinweis:** Diese Variablen werden bei der Erstellung der Frequenztabellen nicht berücksichtigt.

freqtable.ignore = ["text",
		    "eingangsnummer",
		    "datum",
		    "doc_id",
		    "seite",
		    "name",
		    "ecli",
		    "aktenzeichen",
		    "pressemitteilung",
		    "zitiervorschlag",
		    "kurzbeschreibung"]
