version: "3.7"

services:
  c-bverfge:
    container_name: c-bverfge
    image: c-bverfge:4.2.2
    tty: true
    volumes:
      - .:/c-bverfge
      - ./etc/gitconfig:/etc/gitconfig
    environment:
      - TZ=Europe/Berlin